version: '3.8'

services:
#  incident-api:
 #   build: .
  ###  - "3000:3000"
    #depends_on:
    #  - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
     - mongo_db:/data/db 
       
volumes:
  mongo_db:
